name: Build & Run

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Rust stable
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Check out code
      uses: actions/checkout@v2

    - name: Test
      id: test
      uses: actions-rs/cargo@v1
      with:
        command: test

    - name: Build
      id: build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --bins

    - name: Run
      id: run
      run: |
        for e in $(find target/release/ -maxdepth 1 -executable -type f -name 'day*' | sort); do
          echo "## $e" | cut -d/ -f3
          $e
          echo ""
        done > result.txt
        echo "::set-output name=result::$(cat result.txt)\n"

    - name: Send results to discord
      uses: sarisia/actions-status-discord@v1
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        nodetail: true
        description: |
          Result:
          ${{join(steps.run.outputs.*, '\n')}}
