name: Build & Run

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Rust stable
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Check out code
      uses: actions/checkout@v2

    - name: Test
      uses: actions-rs/cargo@v1
      with:
        command: test

    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --bins

    - name: Run
      run: |
        for e in $(find target/release/ -maxdepth 1 -executable -type f -name 'day*'); do
          echo "## $e" | cut -d/ -f3
          $e
          echo ""
        done

    - name: Send results to discord
      uses: sarisia/actions-status-discord@v1
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        description: "${{join(steps.Run.outputs.*, '\n')}}"
